import "./globals.css";
import AuthProvider from "./authcontext/authcontextProvider";
import { IBM_Plex_Sans_Arabic } from "next/font/google";

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-ibm-plex-sans-arabic",
  display: "swap", 
});


export const metadata = {
  title: "Net Go",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar" className={ibmPlexSansArabic.variable}>
      <body>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
